FROM rhscl/s2i-base-rhel7

# This image provides a Ruby 2.5 environment you can use to run your Ruby
# applications.

MAINTAINER Tim Taylor <ttaylor@mitre.org>

EXPOSE 8080

ENV RUBY_VERSION=2.5 \
    YARN_VERSION=1.13.0 \

    SUMMARY="Platform for building and running Ruby $RUBY_VERSION applications" \
    DESCRIPTION="Ruby $RUBY_VERSION available as docker container is a base platform for \
building and running various Ruby $RUBY_VERSION applications and frameworks. \
Ruby is the interpreted scripting language for quick and easy object-oriented programming. \
It has many features to process text files and to do system management tasks (as in Perl). \
It is simple, straight-forward, and extensible."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="Ruby 2.5" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,ruby,ruby25,rh-ruby25" \
      com.redhat.component="rh-ruby25-docker" \
      name="rhscl/ruby-vocab-25-rhel7" \
      version="2.5" \
      release="4.1" \
      maintainer="Tim Taylor <ttaylor@mitre.org>"

#######################
# MITRE Additions
#######################

ENV http_proxy=http://gatekeeper.mitre.org:80/ \
    https_proxy=http://gatekeeper.mitre.org:80/

# Add proxy to environment
COPY proxy.sh /etc/profile.d/

# Add MITRE CA certificates to system trusted store
COPY certs/*.pem /etc/pki/ca-trust/source/anchors/
RUN /usr/bin/update-ca-trust extract

#######################
# end MITRE Additions
#######################

# To use subscription inside container yum command has to be run first (before yum-config-manager)
# https://access.redhat.com/solutions/1443553
RUN yum repolist > /dev/null && \
    yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    yum-config-manager --enable rhel-7-server-optional-rpms && \
    INSTALL_PKGS="rh-ruby25 rh-ruby25-ruby-devel rh-ruby25-rubygem-rake rh-ruby25-rubygem-bundler rh-nodejs10" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && rpm -V $INSTALL_PKGS && \
    wget https://github.com/yarnpkg/yarn/releases/download/v$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz && \
    mkdir -p /opt && \
    tar -C /opt -zxvf yarn-v$YARN_VERSION.tar.gz && \
    rm -rf yarn-v$YARN_VERSION && \
    rm yarn*.tar.gz && \
    ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/bin/yarn && \
    yum clean all -y

# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Copy extra files to the image.
COPY ./root/ /

RUN chown -R 1001:0 /opt/app-root && chmod -R ug+rwx /opt/app-root

USER 1001

# Set the default CMD to print the usage of the language image
CMD $STI_SCRIPTS_PATH/usage
